### PR TITLE
Allow high quality item images

### PR DESCRIPTION
**Pull request by Decimation**
Just tried it out, works great!

### CODE REVIEW

**Comment by DatDrummerGuy** [comment]
Can we see a comparison ? :)

**Comment by Decimation** [comment]
@DatDrummerGuy 

High quality: http://images.akamai.steamusercontent.com/ugc/396677947596749672/158A8DA132EB0A1C32D22F168D3A38FF8AD8DD6A/

Low quality: http://images.akamai.steamusercontent.com/ugc/396677947596749366/2577EF58FA28FA153A75DC445AE6FE2EF8D443D8/

Degreaser and Axtinguisher are a bit more noticable. It's a bit hard to see the difference due to image compression, but once you see it in game the difference is much more noticable.

**Comment by DatDrummerGuy** [comment]
That's pretty cool ! 
I'll turn this on tho, how did you, like, turn the weapons in your loadout slots ? It looks great

**Comment by Decimation** [comment]
@DatDrummerGuy It's a mod. Right here: https://tf2b.com/iconpromo.php

Simply put it in your /custom/ folder

**Comment by DatDrummerGuy** [comment]
Oh, that's awesome, thanks man ! 
Have a great day ;)

**Comment by n0kk** [comment]
Neat. Didn't know about this. I'll have to check it out and may add it next time I update the HUD.

**Comment by n0kk** [comment]
Added https://github.com/n0kk/ahud/commit/38f3cce54514bf6bc2b798b21f64b6888b406a53

**Pull request closed without merging**
